# Generated by Django 2.0.1 on 2018-03-21 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_logs', '0002_namedstormcovereddatalog_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='namedstormcovereddatalog',
            old_name='message',
            new_name='exception',
        ),
    ]
