# Generated by Django 3.1.3 on 2021-02-22 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dems', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demsource',
            name='name',
            field=models.CharField(default='none', max_length=200),
            preserve_default=False,
        ),
    ]
