# Generated by Django 3.1.3 on 2021-02-22 16:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dems', '0002_demsource_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demsourcelog',
            name='date_updated',
        ),
        migrations.AddField(
            model_name='dem',
            name='date_updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='demsourcelog',
            name='date_scanned',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
