# Generated by Django 3.1.3 on 2021-02-22 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dems', '0004_auto_20210222_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demsource',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='demsource',
            name='url',
            field=models.CharField(help_text='ftp scheme', max_length=1000, unique=True),
        ),
    ]
