# Generated by Django 3.1.3 on 2021-02-22 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dems', '0006_auto_20210222_1755'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dem',
            options={'ordering': ('-date_updated',)},
        ),
        migrations.AlterModelOptions(
            name='demsourcelog',
            options={'ordering': ('-date_scanned',)},
        ),
    ]
