# Generated by Django 3.1.3 on 2021-02-22 19:43

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dems', '0007_auto_20210222_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='dem',
            name='boundary',
            field=django.contrib.gis.db.models.fields.PolygonField(geography=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='dem',
            name='crs',
            field=models.CharField(default='nonya', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dem',
            name='resolution',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='demsource',
            name='url',
            field=models.CharField(help_text='FTP scheme', max_length=1000, unique=True),
        ),
    ]
