# Generated by Django 3.1.3 on 2021-02-22 21:15

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dems', '0009_auto_20210222_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dem',
            name='boundary',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, geography=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='dem',
            name='crs',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dem',
            name='resolution',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
