# Generated by Django 3.1.3 on 2021-02-23 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dems', '0010_auto_20210222_2115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dem',
            name='crs',
        ),
    ]
