# Generated by Django 2.0.1 on 2018-09-05 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('named_storms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='namedstormcovereddata',
            name='dates_required',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='covereddata',
            name='url',
            field=models.CharField(blank=True, help_text='Product URL for this dataset', max_length=5000),
        ),
        migrations.AlterField(
            model_name='covereddataprovider',
            name='processor_factory',
            field=models.CharField(blank=True, choices=[('ERDDAP', 'ERDDAP'), ('NDBC', 'NDBC'), ('USGS', 'USGS'), ('JPL_QSCAT_L1C', 'JPL_QSCAT_L1C'), ('JPL_SMAP_L2B', 'JPL_SMAP_L2B'), ('JPL_MET_OP_ASCAT_L2', 'JPL_MET_OP_ASCAT_L2')], help_text='Optionally specify a custom processor factory', max_length=50),
        ),
    ]
