# Generated by Django 2.0.1 on 2018-02-26 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('named_storms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataproviderprocessor',
            name='regex',
        ),
        migrations.AddField(
            model_name='namedstormcovereddataprovider',
            name='data_regex',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
