# Generated by Django 2.0.1 on 2018-03-07 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('named_storms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covereddata',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
