# Generated by Django 2.0.1 on 2018-02-27 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('named_storms', '0002_auto_20180226_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='namedstormcovereddata',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='dataproviderprocessor',
            name='name',
            field=models.CharField(choices=[('dap', 'dap'), ('ndbc', 'ndbc')], max_length=200),
        ),
    ]
