# Generated by Django 2.0.1 on 2018-06-12 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('named_storms', '0002_auto_20180509_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='covereddataprovider',
            name='data_type',
        ),
        migrations.RemoveField(
            model_name='covereddataprovider',
            name='processor',
        ),
        migrations.AddField(
            model_name='covereddataprovider',
            name='processor_factory',
            field=models.CharField(choices=[('ERDDAP', 'ERDDAP'), ('NDBC', 'NDBC'), ('USGS', 'USGS'), ('JPL_QSCAT_L1C', 'JPL_QSCAT_L1C')], default='ERDDAP', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='covereddataprovider',
            name='processor_source',
            field=models.CharField(choices=[('FILE-GENERIC', 'FILE-GENERIC'), ('FILE-BINARY', 'FILE-BINARY'), ('DAP', 'DAP')], default='DAP', max_length=50),
            preserve_default=False,
        ),
    ]
