# Generated by Django 2.0.1 on 2018-03-08 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('named_storms', '0002_auto_20180307_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='covereddataprovider',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='namedstorm',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
