# Generated by Django 2.0.1 on 2018-07-03 13:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('named_storms', '0003_auto_20180612_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='covereddataprovider',
            name='epoch_datetime',
            field=models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='covereddataprovider',
            name='processor_factory',
            field=models.CharField(choices=[('ERDDAP', 'ERDDAP'), ('NDBC', 'NDBC'), ('USGS', 'USGS'), ('JPL_QSCAT_L1C', 'JPL_QSCAT_L1C'), ('JPL_SMAP_L2B', 'JPL_SMAP_L2B'), ('JPL_MET_OP_A_ASCAT_L2', 'JPL_MET_OP_A_ASCAT_L2')], max_length=50),
        ),
        migrations.AlterField(
            model_name='covereddataprovider',
            name='processor_source',
            field=models.CharField(choices=[('FILE-GENERIC', 'FILE-GENERIC'), ('FILE-BINARY', 'FILE-BINARY'), ('DAP', 'DAP'), ('HDF', 'HDF')], max_length=50),
        ),
    ]
