# Generated by Django 2.0.1 on 2018-03-21 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('named_storms', '0003_auto_20180308_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='namedstorm',
            name='latest_snapshot',
            field=models.TextField(blank=True),
        ),
    ]
