# Generated by Django 2.0.1 on 2018-07-11 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('named_storms', '0004_auto_20180703_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='covereddataprovider',
            name='documentation_url',
            field=models.CharField(blank=True, max_length=5000),
        ),
        migrations.AlterField(
            model_name='covereddataprovider',
            name='processor_factory',
            field=models.CharField(choices=[('ERDDAP', 'ERDDAP'), ('NDBC', 'NDBC'), ('USGS', 'USGS'), ('JPL_QSCAT_L1C', 'JPL_QSCAT_L1C'), ('JPL_SMAP_L2B', 'JPL_SMAP_L2B'), ('JPL_MET_OP_ASCAT_L2', 'JPL_MET_OP_ASCAT_L2')], max_length=50),
        ),
        migrations.AlterField(
            model_name='covereddataprovider',
            name='data_url',
            field=models.CharField(max_length=5000),
        ),
    ]
