# Generated by Django 2.0.1 on 2018-03-21 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('named_storms', '0004_namedstorm_latest_snapshot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='namedstorm',
            name='latest_snapshot',
        ),
    ]
