# Generated by Django 2.0.5 on 2018-09-19 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('named_storms', '0005_auto_20180905_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='nsem',
            name='covered_data_logs',
            field=models.ManyToManyField(to='named_storms.NamedStormCoveredDataLog'),
        ),
        migrations.AlterField(
            model_name='covereddataprovider',
            name='processor_factory',
            field=models.CharField(blank=True, choices=[('ERDDAP', 'ERDDAP'), ('NDBC', 'NDBC'), ('USGS', 'USGS'), ('JPL_QSCAT_L1C', 'JPL_QSCAT_L1C'), ('JPL_SMAP_L2B', 'JPL_SMAP_L2B'), ('JPL_MET_OP_ASCAT_L2', 'JPL_MET_OP_ASCAT_L2'), ('TIDES_AND_CURRENTS', 'TIDES_AND_CURRENTS')], help_text='Optionally specify a custom processor factory', max_length=50),
        ),
    ]
