# Generated by Django 2.0.1 on 2018-07-11 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('named_storms', '0005_auto_20180711_1630'),
    ]

    operations = [
        migrations.RenameField(
            model_name='covereddataprovider',
            old_name='url',
            new_name='data_url',
        ),
    ]
