# Generated by Django 2.0.1 on 2018-03-22 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('named_storms', '0005_remove_namedstorm_latest_snapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='NSEM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_requested', models.DateTimeField(auto_now_add=True)),
                ('date_returned', models.DateTimeField(blank=True)),
                ('model_input', models.TextField()),
                ('model_output', models.TextField(blank=True)),
                ('named_storm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='named_storms.NamedStorm')),
            ],
        ),
    ]
