# Generated by Django 2.0.5 on 2018-09-19 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('named_storms', '0006_auto_20180919_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nsem',
            name='date_returned',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
