# Generated by Django 2.0.1 on 2018-07-11 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('named_storms', '0006_auto_20180711_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covereddataprovider',
            name='data_url',
            field=models.CharField(max_length=5000),
        ),
    ]
