# Generated by Django 2.0.1 on 2018-07-11 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('named_storms', '0007_auto_20180711_1637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='covereddataprovider',
            name='documentation_url',
        ),
        migrations.AddField(
            model_name='covereddata',
            name='documentation_url',
            field=models.CharField(blank=True, max_length=5000),
        ),
    ]
