# Generated by Django 2.0.5 on 2018-09-24 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('named_storms', '0007_auto_20180919_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covereddataprovider',
            name='processor_factory',
            field=models.CharField(choices=[('CORE', 'CORE'), ('ERDDAP', 'ERDDAP'), ('NDBC', 'NDBC'), ('USGS', 'USGS'), ('JPL_QSCAT_L1C', 'JPL_QSCAT_L1C'), ('JPL_SMAP_L2B', 'JPL_SMAP_L2B'), ('JPL_MET_OP_ASCAT_L2', 'JPL_MET_OP_ASCAT_L2'), ('TIDES_AND_CURRENTS', 'TIDES_AND_CURRENTS'), ('NATIONAL_WATER_MODEL', 'NATIONAL_WATER_MODEL')], help_text='Optionally specify a custom processor factory', max_length=50),
        ),
        migrations.AlterField(
            model_name='nsem',
            name='covered_data_logs',
            field=models.ManyToManyField(blank=True, to='named_storms.NamedStormCoveredDataLog'),
        ),
    ]
