# Generated by Django 2.0.1 on 2018-03-22 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('named_storms', '0007_auto_20180322_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nsem',
            name='date_returned',
            field=models.DateTimeField(null=True),
        ),
    ]
