# Generated by Django 2.0.1 on 2018-07-11 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('named_storms', '0008_auto_20180711_1712'),
    ]

    operations = [
        migrations.RenameField(
            model_name='covereddata',
            old_name='documentation_url',
            new_name='url',
        ),
        migrations.RenameField(
            model_name='covereddataprovider',
            old_name='data_url',
            new_name='url',
        ),
    ]
