# Generated by Django 2.0.5 on 2018-09-24 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('named_storms', '0008_auto_20180924_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='namedstormcovereddata',
            name='last_successful_log',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='named_storms.NamedStormCoveredDataLog'),
        ),
    ]
