# Generated by Django 2.0.5 on 2018-09-24 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('named_storms', '0009_namedstormcovereddata_last_successful_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='namedstormcovereddata',
            name='last_successful_log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='named_storms.NamedStormCoveredDataLog'),
        ),
    ]
