# Generated by Django 2.0.1 on 2018-03-27 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('named_storms', '0009_auto_20180327_1404'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nsem',
            options={'permissions': (('download_nsem_data', 'Can download data'),)},
        ),
    ]
