# Generated by Django 2.0.1 on 2018-03-27 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('named_storms', '0011_auto_20180327_1416'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nsem',
            old_name='model_input',
            new_name='covered_data_snapshot',
        ),
    ]
