# Generated by Django 2.0.5 on 2018-09-24 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('named_storms', '0011_auto_20180924_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='namedstormcovereddata',
            name='date_collected',
            field=models.DateField(blank=True, null=True),
        ),
    ]
