# Generated by Django 2.0.1 on 2018-03-27 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('named_storms', '0012_auto_20180327_1912'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nsem',
            old_name='model_output',
            new_name='model_output_snapshot',
        ),
    ]
