# Generated by Django 2.0.5 on 2019-04-19 16:16

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('named_storms', '0012_namedstormcovereddata_date_collected'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataContour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geo', django.contrib.gis.db.models.fields.PolygonField(geography=True, srid=4326)),
                ('value', models.FloatField()),
                ('color', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='NsemPsa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nsem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='named_storms.NSEM')),
                ('water_level_max', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='named_storms.DataContour')),
            ],
        ),
    ]
