# Generated by Django 2.0.1 on 2018-03-28 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('named_storms', '0013_auto_20180327_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='namedstormcovereddata',
            name='external_storm_id',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
