# Generated by Django 2.0.1 on 2018-03-28 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('named_storms', '0014_namedstormcovereddata_external_storm_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covereddataprovider',
            name='processor',
            field=models.CharField(choices=[('dap', 'dap'), ('ndbc', 'ndbc'), ('usgs', 'usgs')], max_length=50),
        ),
        migrations.DeleteModel(
            name='DataProviderProcessor',
        ),
    ]
