# Generated by Django 2.0.5 on 2019-04-19 17:35

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('named_storms', '0014_auto_20190419_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datacontour',
            name='geo',
            field=django.contrib.gis.db.models.fields.GeometryField(geography=True, srid=4326),
        ),
    ]
