# Generated by Django 2.0.1 on 2018-03-28 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('named_storms', '0015_auto_20180328_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covereddataprovider',
            name='data_type',
            field=models.CharField(blank=True, choices=[('sequence', 'sequence'), ('grid', 'grid')], max_length=200),
        ),
    ]
