# Generated by Django 2.0.5 on 2019-04-23 16:44

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('named_storms', '0018_auto_20190419_1835'),
    ]

    operations = [
        migrations.CreateModel(
            name='NsemPsaData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('geo', django.contrib.gis.db.models.fields.MultiPolygonField(geography=True, srid=4326)),
                ('value', models.FloatField()),
                ('color', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='NsemPsaVariable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('nsem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='named_storms.NSEM')),
            ],
        ),
        migrations.RemoveField(
            model_name='nsempsa',
            name='nsem',
        ),
        migrations.DeleteModel(
            name='NsemPsa',
        ),
        migrations.AddField(
            model_name='nsempsadata',
            name='nsem_psa_variable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='named_storms.NsemPsaVariable'),
        ),
    ]
