# Generated by Django 2.0.5 on 2019-04-26 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('named_storms', '0022_nsempsavariable_geo_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='nsempsavariable',
            name='data_type',
            field=models.CharField(choices=[('time-series', 'Time Series'), ('max-values', 'Max Values')], default='time-series', max_length=20),
            preserve_default=False,
        ),
    ]
