# Generated by Django 2.0.5 on 2019-04-29 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('named_storms', '0023_nsempsavariable_data_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='nsempsavariable',
            name='units',
            field=models.CharField(choices=[('m', 'm'), ('m/s', 'm/s')], default='m/s', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='nsempsavariable',
            name='data_type',
            field=models.CharField(choices=[('time-series', 'time-series'), ('max-values', 'max-values')], max_length=20),
        ),
        migrations.AlterField(
            model_name='nsempsavariable',
            name='geo_type',
            field=models.CharField(choices=[('multipolygon', 'multipolygon'), ('point', 'point')], max_length=20),
        ),
    ]
