# Generated by Django 2.0.5 on 2019-04-29 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('named_storms', '0024_auto_20190429_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nsempsadata',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
