# Generated by Django 2.0.5 on 2019-04-30 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('named_storms', '0025_auto_20190429_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nsempsadata',
            name='color',
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AlterField(
            model_name='nsempsadata',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
