# Generated by Django 2.0.5 on 2019-04-30 19:44

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('named_storms', '0026_auto_20190430_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nsempsadata',
            name='geo',
            field=django.contrib.gis.db.models.fields.GeometryField(geography=True, srid=4326),
        ),
    ]
