# Generated by Django 2.0.5 on 2019-05-02 17:31

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('named_storms', '0027_auto_20190430_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nsempsavariable',
            name='color_bar',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='nsempsavariable',
            name='geo_type',
            field=models.CharField(choices=[('multipolygon', 'multipolygon'), ('point', 'point'), ('wind-arrow', 'wind-arrow')], max_length=20),
        ),
        migrations.AlterField(
            model_name='nsempsavariable',
            name='units',
            field=models.CharField(choices=[('m/s', 'm/s'), ('m', 'm'), ('rad', 'rad')], max_length=20),
        ),
    ]
