# Generated by Django 2.0.5 on 2019-05-14 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('named_storms', '0028_auto_20190502_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='nsempsavariable',
            name='auto_displayed',
            field=models.BooleanField(default=False),
        ),
    ]
