# Generated by Django 2.0.5 on 2019-05-17 21:46

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('named_storms', '0029_nsempsavariable_auto_displayed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nsempsavariable',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='nsempsadata',
            name='bbox',
            field=django.contrib.gis.db.models.fields.GeometryField(geography=True, null=True, srid=4326),
        ),
    ]
