# Generated by Django 2.0.5 on 2019-05-20 17:59

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('named_storms', '0031_auto_20190517_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='nsem',
            name='dates',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateTimeField(), default=list, size=None),
        ),
    ]
