# Generated by Django 2.0.5 on 2019-05-20 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('named_storms', '0032_nsem_dates'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='nsempsadata',
            index=models.Index(fields=['nsem_psa_variable', 'date'], name='named_storm_nsem_ps_79e775_idx'),
        ),
    ]
