# Generated by Django 2.0.5 on 2019-05-21 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('named_storms', '0033_auto_20190520_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='namedstorm',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='nsempsavariable',
            name='geo_type',
            field=models.CharField(choices=[('polygon', 'polygon'), ('point', 'point'), ('wind-arrow', 'wind-arrow')], max_length=20),
        ),
    ]
