# Generated by Django 2.0.5 on 2019-06-05 18:06

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('named_storms', '0034_auto_20190521_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='nsempsadata',
            name='meta',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
    ]
