# Generated by Django 2.0.5 on 2019-06-17 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('named_storms', '0035_nsempsadata_meta'),
    ]

    operations = [
        migrations.AddField(
            model_name='nsempsadata',
            name='geo_hash',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='nsempsavariable',
            name='geo_type',
            field=models.CharField(choices=[('polygon', 'polygon'), ('wind-barb', 'wind-barb')], max_length=20),
        ),
    ]
