# Generated by Django 2.0.5 on 2019-06-17 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('named_storms', '0036_auto_20190617_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nsempsadata',
            name='geo_hash',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddIndex(
            model_name='nsempsadata',
            index=models.Index(fields=['nsem_psa_variable', 'geo_hash'], name='named_storm_nsem_ps_89dfad_idx'),
        ),
    ]
