# Generated by Django 2.0.5 on 2019-06-28 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('named_storms', '0037_auto_20190617_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nsempsavariable',
            name='units',
            field=models.CharField(choices=[('m/s', 'm/s'), ('m', 'm'), ('degree', 'degree')], max_length=20),
        ),
    ]
