# Generated by Django 2.0.5 on 2019-07-12 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('named_storms', '0039_auto_20190628_1936'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='nsempsavariable',
            unique_together={('nsem', 'name', 'data_type')},
        ),
    ]
