# Generated by Django 2.0.5 on 2019-07-15 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('named_storms', '0040_auto_20190712_1858'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='nsempsavariable',
            unique_together={('nsem', 'name')},
        ),
    ]
