# Generated by Django 2.0.5 on 2019-08-01 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('named_storms', '0041_auto_20190715_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='nsempsavariable',
            name='element_type',
            field=models.CharField(choices=[('water', 'water'), ('wind', 'wind')], default='water', max_length=20),
            preserve_default=False,
        ),
    ]
