# Generated by Django 2.0.5 on 2019-08-12 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('named_storms', '0042_nsempsavariable_element_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='NsemPsaUserExport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=1500)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_completed', models.DateTimeField(blank=True, null=True)),
                ('nsem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='named_storms.NSEM')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
