# Generated by Django 2.0.5 on 2019-08-12 15:55

import django.contrib.gis.db.models.fields
from django.db import migrations
from django.contrib.gis.geos import Polygon


class Migration(migrations.Migration):

    dependencies = [
        ('named_storms', '0044_nsempsauserexport_date_expires'),
    ]

    operations = [
        migrations.AddField(
            model_name='nsempsauserexport',
            name='bbox',
            # dummy polygon to satisfy django's migrate
            field=django.contrib.gis.db.models.fields.GeometryField(default=Polygon([[0, 0], [1, 1], [2, 2], [0, 0]]), geography=True, srid=4326),
            preserve_default=False,
        ),
    ]
