# Generated by Django 2.0.5 on 2019-08-12 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('named_storms', '0045_nsempsauserexport_bbox'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NSEM',
            new_name='NsemPsa',
        ),
    ]
