# Generated by Django 2.0.5 on 2019-08-13 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('named_storms', '0046_auto_20190812_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nsempsauserexport',
            name='url',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
    ]
