# Generated by Django 2.0.5 on 2019-08-13 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('named_storms', '0047_auto_20190813_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nsempsauserexport',
            name='date_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
