# Generated by Django 2.0.5 on 2019-08-19 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('named_storms', '0048_auto_20190813_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='nsempsauserexport',
            name='format',
            field=models.CharField(choices=[('netcdf', 'netcdf'), ('shapefile', 'shapefile')], default='netcdf', max_length=30),
            preserve_default=False,
        ),
    ]
