# Generated by Django 2.0.5 on 2019-08-20 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('named_storms', '0049_nsempsauserexport_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='nsempsauserexport',
            name='date_filter',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nsempsauserexport',
            name='format',
            field=models.CharField(choices=[('netcdf', 'netcdf'), ('shapefile', 'shapefile'), ('csv', 'csv')], max_length=30),
        ),
    ]
