# Generated by Django 2.0.5 on 2019-09-04 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('named_storms', '0050_auto_20190820_1459'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='nsempsadata',
            name='named_storm_nsem_ps_79e775_idx',
        ),
        migrations.AddIndex(
            model_name='nsempsadata',
            index=models.Index(fields=['nsem_psa_variable', 'date', 'value'], name='named_storm_nsem_ps_ba5d2d_idx'),
        ),
    ]
