# Generated by Django 2.0.5 on 2019-09-11 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('named_storms', '0051_auto_20190904_1812'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nsempsa',
            old_name='covered_data_snapshot',
            new_name='covered_data_snapshot_path',
        ),
        migrations.RenameField(
            model_name='nsempsa',
            old_name='model_output_snapshot',
            new_name='model_output_snapshot_path',
        ),
        migrations.AddField(
            model_name='nsempsa',
            name='date_processed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
