# Generated by Django 2.0.5 on 2019-09-11 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('named_storms', '0052_auto_20190911_1559'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nsempsa',
            old_name='model_output_snapshot_extracted',
            new_name='psa_snapshot_extracted',
        ),
        migrations.RenameField(
            model_name='nsempsa',
            old_name='model_output_snapshot_path',
            new_name='psa_snapshot_path',
        ),
    ]
