# Generated by Django 2.0.5 on 2019-09-11 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('named_storms', '0054_auto_20190911_2051'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nsempsa',
            old_name='date_psa_processed',
            new_name='date_processsed',
        ),
        migrations.RenameField(
            model_name='nsempsa',
            old_name='psa_snapshot_extracted',
            new_name='snapshot_extracted',
        ),
        migrations.RenameField(
            model_name='nsempsa',
            old_name='psa_snapshot_path',
            new_name='snapshot_path',
        ),
    ]
