# Generated by Django 2.0.5 on 2019-09-20 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('named_storms', '0056_auto_20190917_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nsempsauserexport',
            name='format',
            field=models.CharField(choices=[('netcdf', 'netcdf'), ('shapefile', 'shapefile'), ('geojson', 'geojson'), ('kml', 'kml'), ('csv', 'csv')], max_length=30),
        ),
    ]
