# Generated by Django 2.0.5 on 2019-09-23 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('named_storms', '0057_auto_20190920_1901'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nsempsa',
            old_name='date_processsed',
            new_name='date_processed',
        ),
    ]
