# Generated by Django 2.0.5 on 2019-09-24 19:31

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('named_storms', '0059_auto_20190924_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='nsempsa',
            name='validation_exceptions',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
    ]
