# Generated by Django 2.0.5 on 2019-09-24 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('named_storms', '0060_nsempsa_validation_exceptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='nsempsa',
            name='validated',
            field=models.BooleanField(default=False),
        ),
    ]
