# Generated by Django 2.0.5 on 2019-09-26 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('named_storms', '0061_nsempsa_validated'),
    ]

    operations = [
        migrations.AddField(
            model_name='nsempsa',
            name='covered_data_snapshot_created',
            field=models.BooleanField(default=False),
        ),
    ]
