# Generated by Django 2.0.5 on 2019-09-26 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('named_storms', '0062_nsempsa_covered_data_snapshot_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='nsempsa',
            name='date_processed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
