# Generated by Django 2.0.5 on 2019-09-26 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('named_storms', '0063_nsempsa_date_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='nsempsa',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
