# Generated by Django 2.0.5 on 2019-09-27 15:12

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('named_storms', '0064_nsempsa_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='nsempsa',
            name='validated_files',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), default=list, size=None),
        ),
    ]
