# Generated by Django 2.0.5 on 2019-10-01 14:13

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('named_storms', '0065_nsempsa_validated_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nsempsa',
            name='validated_files',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, size=None),
        ),
    ]
