# Generated by Django 2.0.5 on 2019-10-03 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('named_storms', '0068_auto_20191003_1520'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nsempsa',
            old_name='snapshot_path',
            new_name='path',
        ),
    ]
