# Generated by Django 2.2.6 on 2019-10-04 15:42

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('named_storms', '0069_auto_20191003_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='nsempsa',
            name='manifest',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
    ]
