# Generated by Django 2.2.6 on 2019-10-04 15:43

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('named_storms', '0070_nsempsa_manifest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nsempsa',
            name='manifest',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
