# Generated by Django 2.2.6 on 2019-10-04 15:53

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('named_storms', '0072_auto_20191004_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nsempsa',
            name='manifest',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
