# Generated by Django 2.2.6 on 2019-10-15 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('named_storms', '0074_auto_20191008_1630'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nsempsa',
            old_name='date_requested',
            new_name='date_created',
        ),
    ]
