# Generated by Django 2.2.6 on 2019-10-15 19:45

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('named_storms', '0075_auto_20191015_1713'),
    ]

    operations = [
        migrations.CreateModel(
            name='NsemPsaManifestDataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=200)),
                ('variables', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), default=list, size=None)),
                ('dates', django.contrib.postgres.fields.ArrayField(base_field=models.DateTimeField(), default=list, size=None)),
                ('nsem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='named_storms.NsemPsa')),
            ],
        ),
    ]
