# Generated by Django 2.2.6 on 2019-10-16 15:50

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('named_storms', '0076_nsempsamanifestdataset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nsempsamanifestdataset',
            name='dates',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateTimeField(), size=None),
        ),
        migrations.AlterField(
            model_name='nsempsamanifestdataset',
            name='variables',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), size=None),
        ),
    ]
