# Generated by Django 2.2.6 on 2019-10-17 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('named_storms', '0077_auto_20191016_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nsempsa',
            name='covered_data_logs',
        ),
        migrations.RemoveField(
            model_name='nsempsa',
            name='covered_data_snapshot_created',
        ),
        migrations.RemoveField(
            model_name='nsempsa',
            name='covered_data_snapshot_path',
        ),
        migrations.CreateModel(
            name='NamedStormCoveredDataSnapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_requested', models.DateTimeField(auto_now_add=True)),
                ('date_completed', models.DateTimeField(blank=True, null=True)),
                ('path', models.CharField(max_length=500)),
                ('covered_data_logs', models.ManyToManyField(blank=True, to='named_storms.NamedStormCoveredDataLog')),
                ('named_storm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='named_storms.NamedStorm')),
            ],
        ),
    ]
