# Generated by Django 2.2.6 on 2019-10-22 17:30

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('named_storms', '0079_nsempsa_covered_data_snapshot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nsempsa',
            name='date_returned',
        ),
        migrations.AlterField(
            model_name='namedstormcovereddatasnapshot',
            name='path',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='nsempsa',
            name='covered_data_snapshot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='named_storms.NamedStormCoveredDataSnapshot'),
        ),
        migrations.AlterField(
            model_name='nsempsa',
            name='manifest',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
        migrations.AlterField(
            model_name='nsempsa',
            name='path',
            field=models.TextField(),
        ),
    ]
