# Generated by Django 2.2.6 on 2019-10-22 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('named_storms', '0081_auto_20191022_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nsempsa',
            name='covered_data_snapshot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='named_storms.NamedStormCoveredDataSnapshot'),
        ),
    ]
