# Generated by Django 2.2.6 on 2019-10-23 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('named_storms', '0083_auto_20191023_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='namedstormcovereddatalog',
            name='date_completed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
