# Generated by Django 2.2.6 on 2019-10-28 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('named_storms', '0084_namedstormcovereddatalog_date_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nsempsa',
            name='validated_files',
        ),
    ]
