# Generated by Django 2.2.6 on 2019-10-29 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('named_storms', '0087_auto_20191028_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='nsempsavariable',
            name='display_name',
            field=models.CharField(choices=[('Water Level', 'Water Level'), ('Water Level Max', 'Water Level Max'), ('Wave Height', 'Wave Height'), ('Wind Speed', 'Wind Speed'), ('Wind Speed Max', 'Wind Speed Max'), ('Wind Barbs', 'Wind Barbs')], default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='nsempsavariable',
            name='name',
            field=models.CharField(choices=[('water_level', 'Water Level'), ('water_level_max', 'Water Level Max'), ('wave_height', 'Wave Height'), ('wind_speed', 'Wind Speed'), ('wind_speed_max', 'Wind Speed Max'), ('wind_direction', 'Wind Barbs')], max_length=50),
        ),
    ]
