# Generated by Django 2.2.6 on 2019-10-31 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('named_storms', '0088_auto_20191029_2018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nsempsamanifestdataset',
            name='dates',
        ),
        migrations.AlterField(
            model_name='nsempsavariable',
            name='name',
            field=models.CharField(choices=[('water_level', 'water_level'), ('wave_height', 'wave_height'), ('wind_speed', 'wind_speed'), ('wind_direction', 'wind_direction'), ('water_level_max', 'water_level_max'), ('wind_speed_max', 'wind_speed_max')], max_length=50),
        ),
    ]
