# Generated by Django 2.2.6 on 2019-11-06 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('named_storms', '0089_auto_20191031_1904'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='namedstorm',
            options={'ordering': ['-date_start']},
        ),
        migrations.AlterField(
            model_name='nsempsavariable',
            name='display_name',
            field=models.CharField(choices=[('Water Level', 'Water Level'), ('Wave Height', 'Wave Height'), ('Wind Speed', 'Wind Speed'), ('Wind Barbs', 'Wind Barbs')], max_length=50),
        ),
    ]
