# Generated by Django 3.0.2 on 2020-01-21 21:16

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('named_storms', '0090_auto_20191106_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nsempsadata',
            name='bbox',
            field=django.contrib.gis.db.models.fields.GeometryField(geography=True, null=True, srid=4326),
        ),
    ]
