# Generated by Django 3.0.5 on 2020-05-01 19:44

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('named_storms', '0091_auto_20200121_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nsempsadata',
            name='bbox',
            field=django.contrib.gis.db.models.fields.GeometryField(null=True, srid=4326),
        ),
    ]
