# Generated by Django 3.0.5 on 2020-07-29 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('named_storms', '0091_auto_20200121_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nsempsavariable',
            name='display_name',
            field=models.CharField(choices=[('Water Level', 'Water Level'), ('Wave Height', 'Wave Height'), ('Wind Speed', 'Wind Speed'), ('Wind Gust', 'Wind Gust'), ('Wind Barbs', 'Wind Barbs')], max_length=50),
        ),
        migrations.AlterField(
            model_name='nsempsavariable',
            name='name',
            field=models.CharField(choices=[('water_level', 'water_level'), ('wave_height', 'wave_height'), ('wind_speed', 'wind_speed'), ('wind_direction', 'wind_direction'), ('water_level_max', 'water_level_max'), ('wind_gust', 'wind_gust')], max_length=50),
        ),
    ]
