# Generated by Django 3.0.5 on 2020-08-03 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('named_storms', '0092_auto_20200729_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nsempsavariable',
            name='name',
            field=models.CharField(choices=[('water_level', 'water_level'), ('water_level_max', 'water_level_max'), ('wave_height', 'wave_height'), ('wind_speed', 'wind_speed'), ('wind_direction', 'wind_direction'), ('wind_gust', 'wind_gust')], max_length=50),
        ),
    ]
