# Generated by Django 3.0.5 on 2020-08-15 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('named_storms', '0093_auto_20200803_1248'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='nsempsadata',
            name='named_storm_nsem_ps_ba5d2d_idx',
        ),
        migrations.AlterUniqueTogether(
            name='nsempsadata',
            unique_together={('nsem_psa_variable', 'date', 'value')},
        ),
    ]
