# Generated by Django 3.0.5 on 2020-08-24 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('named_storms', '0093_auto_20200803_1248'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='nsempsadata',
            name='named_storm_nsem_ps_89dfad_idx',
        ),
        migrations.RemoveField(
            model_name='nsempsadata',
            name='geo_hash',
        ),
    ]
