# Generated by Django 3.0.5 on 2020-08-19 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('named_storms', '0094_auto_20200815_1938'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='nsempsadata',
            name='named_storm_nsem_ps_89dfad_idx',
        ),
        migrations.AlterUniqueTogether(
            name='nsempsadata',
            unique_together={('nsem_psa_variable', 'geo_hash', 'date', 'value')},
        ),
    ]
