# Generated by Django 3.0.5 on 2020-08-24 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('named_storms', '0094_auto_20200824_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nsempsadata',
            name='bbox',
        ),
    ]
