# Generated by Django 3.0.5 on 2020-08-24 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('named_storms', '0095_remove_nsempsadata_bbox'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NsemPsaData',
            new_name='NsemPsaContour',
        ),
        migrations.RemoveIndex(
            model_name='nsempsacontour',
            name='named_storms_nsempsadata_nsem_psa_variable_id_bb03d195',
        ),
        migrations.RemoveIndex(
            model_name='nsempsacontour',
            name='named_storm_nsem_ps_ba5d2d_idx',
        ),
        migrations.AddIndex(
            model_name='nsempsacontour',
            index=models.Index(fields=['nsem_psa_variable', 'date', 'value'], name='named_storm_nsem_ps_8cc90b_idx'),
        ),
    ]
