# Generated by Django 3.0.5 on 2020-08-19 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('named_storms', '0095_auto_20200819_1759'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='nsempsadata',
            unique_together={('nsem_psa_variable', 'date', 'value')},
        ),
        migrations.RemoveField(
            model_name='nsempsadata',
            name='geo_hash',
        ),
    ]
