# Generated by Django 3.0.5 on 2020-08-24 23:39

from django.db import migrations


# NOTE:  Created this migration but then made the working change (removing index) in 0098_nsempsadata.py


class Migration(migrations.Migration):

    dependencies = [
        ('named_storms', '0096_auto_20200824_2007'),
    ]

    operations = [
    ]
