# Generated by Django 3.0.5 on 2020-08-24 23:40

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('named_storms', '0097_auto_20200824_2339'),
    ]

    operations = [
        # Renaming a model and creating an identical one requires removing it's index
        # https://code.djangoproject.com/ticket/23577
        migrations.RunSQL("DROP INDEX IF EXISTS named_storms_nsempsadata_nsem_psa_variable_id_bb03d195"),
        migrations.CreateModel(
            name='NsemPsaData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('date', models.DateTimeField()),
                ('value', models.FloatField()),
                ('nsem_psa_variable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='named_storms.NsemPsaVariable')),
            ],
        ),
    ]
