# Generated by Django 3.0.5 on 2020-08-24 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('named_storms', '0098_nsempsadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nsempsadata',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
