# Generated by Django 3.0.5 on 2020-08-27 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('named_storms', '0102_auto_20200827_1757'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='nsempsadata',
            name='named_storm_nsem_ps_a521c8_idx',
        ),
        migrations.RemoveField(
            model_name='nsempsadata',
            name='geo_hash',
        ),
        migrations.AddIndex(
            model_name='nsempsadata',
            index=models.Index(fields=['nsem_psa_variable', 'point', 'date', 'value'], name='named_storm_nsem_ps_395346_idx'),
        ),
    ]
