# Generated by Django 3.0.5 on 2020-09-15 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('named_storms', '0107_auto_20200915_2020'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='nsempsadata',
            name='named_storm_nsem_ps_74649d_idx',
        ),
        migrations.AddIndex(
            model_name='nsempsadata',
            index=models.Index(fields=['nsem_psa_variable', 'date', 'value'], name='named_storm_nsem_ps_ba5d2d_idx'),
        ),
    ]
