# Generated by Django 3.0.5 on 2020-11-02 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('named_storms', '0109_auto_20200916_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='nsempsamanifestdataset',
            name='structured',
            field=models.BooleanField(default=True, help_text='Whether the dataset has a structured grid'),
        ),
    ]
