# Generated by Django 3.0.5 on 2020-11-02 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('named_storms', '0110_nsempsamanifestdataset_structured'),
    ]

    operations = [
        migrations.AddField(
            model_name='nsempsamanifestdataset',
            name='topology_name',
            field=models.CharField(default='element', help_text='Variable name for unstructured mesh connectivity', max_length=50),
        ),
    ]
