# Generated by Django 3.0.5 on 2020-11-21 14:32

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('named_storms', '0112_nsempsavariable_meta'),
    ]

    operations = [
        migrations.AddField(
            model_name='nsempsamanifestdataset',
            name='meta',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
    ]
