# Generated by Django 3.1.3 on 2020-11-30 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('named_storms', '0114_auto_20201126_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='nsempsauserexport',
            name='success',
            field=models.BooleanField(default=False),
        ),
    ]
