# Generated by Django 3.1.3 on 2020-12-02 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('named_storms', '0116_nsempsauserexport_exception'),
    ]

    operations = [
        migrations.AddField(
            model_name='nsempsamanifestdataset',
            name='meta_lat',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='nsempsamanifestdataset',
            name='meta_lon',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='nsempsamanifestdataset',
            name='meta_time',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
