# Generated by Django 3.1.3 on 2020-12-08 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('named_storms', '0117_auto_20201202_2040'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nsempsamanifestdataset',
            options={'ordering': ['-id']},
        ),
    ]
