# Generated by Django 3.1.3 on 2022-05-22 19:51

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import psqlextra.backend.migrations.operations.add_default_partition
import psqlextra.backend.migrations.operations.create_partitioned_model
import psqlextra.manager.manager
import psqlextra.models.partitioned
import psqlextra.types


class Migration(migrations.Migration):

    dependencies = [
        ('named_storms', '0118_auto_20201208_1755'),
    ]

    operations = [
        psqlextra.backend.migrations.operations.create_partitioned_model.PostgresCreatePartitionedModel(
            name='NsemPsaDataPartition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storm_name', models.CharField(db_index=True, max_length=50)),
                ('point', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('value', models.FloatField()),
                ('nsem_psa_variable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='named_storms.nsempsavariable')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            partitioning_options={
                'method': psqlextra.types.PostgresPartitioningMethod['LIST'],
                'key': ['storm_name'],
            },
            bases=(psqlextra.models.partitioned.PostgresPartitionedModel,),
            managers=[
                ('objects', psqlextra.manager.manager.PostgresManager()),
            ],
        ),
        psqlextra.backend.migrations.operations.add_default_partition.PostgresAddDefaultPartition(
            model_name='NsemPsaDataPartition',
            name='default',
        ),
    ]
