# Generated by Django 3.1.3 on 2022-05-24 17:27

from django.db import migrations
from django.db.migrations import RenameModel


class Migration(migrations.Migration):

    dependencies = [
        ('named_storms', '0120_auto_20220522_1953'),
    ]

    operations = [
        RenameModel(old_name='NsemPsaData', new_name='NsemPsaDataOld'),
        RenameModel(old_name='NsemPsaDataPartition', new_name='NsemPsaData')
    ]
