# Generated by Django 2.0.5 on 2018-11-29 18:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ThreddsRequestLog',
            new_name='OpenDapRequestLog',
        ),
    ]
