# Generated by Django 2.0.1 on 2018-02-02 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoveredData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CoveredDataProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.TextField()),
                ('output', models.CharField(max_length=255)),
                ('covered_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='covered_data.CoveredData')),
            ],
        ),
        migrations.CreateModel(
            name='NamedStorm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='covereddata',
            name='named_storm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='covered_data.NamedStorm'),
        ),
    ]
