# Generated by Django 2.0.1 on 2018-02-02 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covered_data', '0002_auto_20180202_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='covereddataprovider',
            name='name',
            field=models.CharField(default='', max_length=500, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='covereddata',
            name='name',
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='covereddataprovider',
            name='output',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='namedstorm',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
