# Generated by Django 2.0.1 on 2018-02-02 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covered_data', '0003_auto_20180202_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covereddataprovider',
            name='name',
            field=models.CharField(max_length=500),
        ),
    ]
