# Generated by Django 2.0.1 on 2018-02-02 18:12

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covered_data', '0004_auto_20180202_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='namedstorm',
            name='poly',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326),
        ),
    ]
