# Generated by Django 2.0.1 on 2018-02-05 14:48

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covered_data', '0006_auto_20180202_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='namedstorm',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326),
        ),
    ]
