# Generated by Django 2.0.1 on 2018-02-05 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covered_data', '0007_namedstorm_geom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='namedstorm',
            name='geom',
        ),
    ]
