# Generated by Django 2.0.1 on 2018-02-05 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covered_data', '0008_remove_namedstorm_geom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='covereddataprovider',
            name='covered_data',
        ),
        migrations.RemoveField(
            model_name='covereddataprovider',
            name='output',
        ),
        migrations.AddField(
            model_name='covereddata',
            name='providers',
            field=models.ManyToManyField(to='covered_data.CoveredDataProvider'),
        ),
    ]
