# Generated by Django 2.0.1 on 2018-02-06 17:23

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('covered_data', '0009_auto_20180205_2029'),
    ]

    operations = [
        migrations.CreateModel(
            name='NamedStormCoveredData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='NamedStormCoveredDataProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('dataset_id', models.CharField(blank=True, max_length=200)),
                ('source', models.TextField()),
                ('variables', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list, size=None)),
                ('constraints', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('covered_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='covered_data.NamedStormCoveredData')),
            ],
        ),
        migrations.RemoveField(
            model_name='covereddata',
            name='named_storm',
        ),
        migrations.RemoveField(
            model_name='covereddata',
            name='providers',
        ),
        migrations.AddField(
            model_name='namedstorm',
            name='date_end',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='namedstorm',
            name='date_start',
            field=models.DateTimeField(null=True),
        ),
        migrations.DeleteModel(
            name='CoveredData',
        ),
        migrations.DeleteModel(
            name='CoveredDataProvider',
        ),
        migrations.AddField(
            model_name='namedstormcovereddata',
            name='named_storm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='covered_data.NamedStorm'),
        ),
    ]
