# Generated by Django 2.0.1 on 2018-02-06 17:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('covered_data', '0010_auto_20180206_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='namedstorm',
            name='date_end',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 6, 17, 27, 17, 643785, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='namedstorm',
            name='date_start',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 6, 17, 27, 31, 907277, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
