# Generated by Django 2.0.1 on 2018-02-06 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covered_data', '0011_auto_20180206_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='namedstormcovereddataprovider',
            name='provider_class',
            field=models.CharField(default='covered_data.providers.ERDDAPBaseCollector', max_length=150),
            preserve_default=False,
        ),
    ]
