# Generated by Django 2.0.1 on 2018-02-06 17:45

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covered_data', '0012_namedstormcovereddataprovider_provider_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='namedstorm',
            name='geo',
            field=django.contrib.gis.db.models.fields.GeometryField(default=None, geography=True, srid=4326),
            preserve_default=False,
        ),
    ]
