# Generated by Django 2.0.1 on 2018-02-06 18:12

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covered_data', '0013_auto_20180206_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='namedstormcovereddataprovider',
            name='variables',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), default=list, size=None),
        ),
    ]
