# Generated by Django 2.0.1 on 2018-02-06 18:14

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covered_data', '0014_auto_20180206_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='namedstormcovereddataprovider',
            name='constraints',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='namedstormcovereddataprovider',
            name='source',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='namedstormcovereddataprovider',
            name='variables',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None),
        ),
    ]
