# Generated by Django 2.0.1 on 2018-02-07 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covered_data', '0015_auto_20180206_1814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='namedstormcovereddataprovider',
            name='constraints',
        ),
        migrations.RemoveField(
            model_name='namedstormcovereddataprovider',
            name='variables',
        ),
        migrations.AddField(
            model_name='namedstormcovereddataprovider',
            name='latitude_constraint',
            field=models.CharField(default='latitude', max_length=50),
        ),
        migrations.AddField(
            model_name='namedstormcovereddataprovider',
            name='longitude_constraint',
            field=models.CharField(default='longitude', max_length=50),
        ),
        migrations.AddField(
            model_name='namedstormcovereddataprovider',
            name='time_constraint',
            field=models.CharField(default='time', max_length=50),
        ),
    ]
