# Generated by Django 2.0.1 on 2018-02-07 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covered_data', '0016_auto_20180207_2006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='namedstormcovereddataprovider',
            old_name='latitude_constraint',
            new_name='latitude_dimension',
        ),
        migrations.RenameField(
            model_name='namedstormcovereddataprovider',
            old_name='longitude_constraint',
            new_name='longitude_dimension',
        ),
        migrations.RenameField(
            model_name='namedstormcovereddataprovider',
            old_name='time_constraint',
            new_name='time_dimension',
        ),
    ]
