# Generated by Django 2.0.1 on 2018-02-08 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covered_data', '0018_remove_namedstormcovereddataprovider_dataset_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='namedstormcovereddataprovider',
            name='latitude_dimension',
        ),
        migrations.RemoveField(
            model_name='namedstormcovereddataprovider',
            name='longitude_dimension',
        ),
        migrations.RemoveField(
            model_name='namedstormcovereddataprovider',
            name='time_dimension',
        ),
    ]
