# Generated by Django 2.0.1 on 2018-02-12 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covered_data', '0019_auto_20180208_1358'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataProviderProcessor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processor_class', models.CharField(max_length=200)),
            ],
        ),
    ]
