# Generated by Django 2.0.1 on 2018-02-12 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covered_data', '0021_auto_20180212_1413'),
    ]

    operations = [
        migrations.RenameField(
            model_name='namedstormcovereddataprovider',
            old_name='processor_class',
            new_name='processor',
        ),
    ]
