# Generated by Django 2.0.1 on 2018-02-12 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covered_data', '0022_auto_20180212_1414'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataproviderprocessor',
            old_name='name',
            new_name='processor_class',
        ),
    ]
