# Generated by Django 2.0.1 on 2018-02-12 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covered_data', '0023_auto_20180212_1418'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataproviderprocessor',
            old_name='processor_class',
            new_name='name',
        ),
    ]
