# Generated by Django 2.0.1 on 2018-02-12 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covered_data', '0024_auto_20180212_1431'),
    ]

    operations = [
        migrations.RenameField(
            model_name='namedstormcovereddataprovider',
            old_name='source',
            new_name='url',
        ),
        migrations.AlterField(
            model_name='dataproviderprocessor',
            name='name',
            field=models.CharField(choices=[('griddap', 'griddap'), ('tabledap', 'tabledap')], max_length=200),
        ),
    ]
