# Generated by Django 2.0.1 on 2018-02-12 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covered_data', '0025_auto_20180212_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='namedstormcovereddataprovider',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
