# Generated by Django 2.0.1 on 2018-02-12 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covered_data', '0026_namedstormcovereddataprovider_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataproviderprocessor',
            name='name',
            field=models.CharField(choices=[('sequence', 'sequence'), ('grid', 'grid')], max_length=200),
        ),
    ]
