# Generated by Django 2.0.1 on 2018-02-12 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covered_data', '0027_auto_20180212_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='namedstormcovereddataprovider',
            name='active',
            field=models.BooleanField(),
        ),
    ]
