# Generated by Django 2.0.1 on 2018-02-13 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covered_data', '0029_auto_20180213_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='namedstormcovereddata',
            name='lat_end',
            field=models.FloatField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='namedstormcovereddata',
            name='lat_start',
            field=models.FloatField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='namedstormcovereddata',
            name='lng_end',
            field=models.FloatField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='namedstormcovereddata',
            name='lng_start',
            field=models.FloatField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='namedstormcovereddata',
            name='time_end',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='namedstormcovereddata',
            name='time_start',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
    ]
