# Generated by Django 2.0.1 on 2018-02-13 20:49

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covered_data', '0031_auto_20180213_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='namedstormcovereddata',
            name='lat_end',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='namedstormcovereddata',
            name='lat_start',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='namedstormcovereddata',
            name='lng_end',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='namedstormcovereddata',
            name='lng_start',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
    ]
