# Generated by Django 2.0.1 on 2018-02-14 14:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covered_data', '0033_auto_20180213_2051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='namedstormcovereddata',
            name='time_end',
        ),
        migrations.RemoveField(
            model_name='namedstormcovereddata',
            name='time_start',
        ),
        migrations.AddField(
            model_name='namedstormcovereddata',
            name='date_end',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='namedstormcovereddata',
            name='date_start',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
