# Generated by Django 2.0.1 on 2018-02-14 15:05

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covered_data', '0034_auto_20180214_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='namedstormcovereddata',
            name='date_end',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='namedstormcovereddata',
            name='date_start',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='namedstormcovereddata',
            name='geo',
            field=django.contrib.gis.db.models.fields.GeometryField(default=None, geography=True, srid=4326),
            preserve_default=False,
        ),
    ]
