# ALPHA
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
spec:
  rules:
  - host: alpha.cwwed-staging.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: cwwed-alpha
            port:
              number: 80
  ingressClassName: nginx
---
