# Generated by Django 2.0.5 on 2018-10-10 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coastal_act', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ComponentProject',
            new_name='CoastalActProject',
        ),
    ]
